 INSERT INTO wms_activities (dc, ucl_user_id, date_time, duration, shift, trx_id, trx_scope, trx_code, trx_type, menu_name, task_main, task_sub, directed, calculated, from_locn_hdr_id, to_locn_hdr_id, item_id, storage_type, quantity, cartons, lpn_number, wave_number, reference_number)
      VALUES ?
ON DUPLICATE KEY UPDATE dc = VALUES(dc)
                      , ucl_user_id = VALUES(ucl_user_id)
                      , date_time = VALUES(date_time)
                      , duration = VALUES(duration)
                      , shift = VALUES(shift)
                      , trx_scope = VALUES(trx_scope)
                      , trx_code = VALUES(trx_code)
                      , trx_type = VALUES(trx_type)
                      , menu_name = VALUES(menu_name)
                      , task_main = VALUES(task_main)
                      , task_sub = VALUES(task_sub)
                      , directed = VALUES(directed)
                      , calculated = VALUES(calculated)
                      , from_locn_hdr_id = VALUES(from_locn_hdr_id)
                      , to_locn_hdr_id = VALUES(to_locn_hdr_id)
                      , item_id = VALUES(item_id)
                      , storage_type = VALUES(storage_type)
                      , quantity = VALUES(quantity)
                      , cartons = VALUES(cartons)
                      , lpn_number = VALUES(lpn_number)
                      , wave_number = VALUES(wave_number)
                      , reference_number = VALUES(reference_number)