 INSERT INTO receiving (dc, bp_id, po_number, po_type, po_date, po_status, sku_count, po_quantity, received_quantity, po_value, received_value, first_received, last_received, verified)
      VALUES ?
ON DUPLICATE KEY UPDATE dc = VALUES(dc)
                      , bp_id = VALUES(bp_id)
                      , po_type = VALUES(po_type)
                      , po_date = VALUES(po_date)
                      , po_status = VALUES(po_status)
                      , sku_count = VALUES(sku_count)
                      , po_quantity = VALUES(po_quantity)
                      , received_quantity = VALUES(received_quantity)
                      , po_value = VALUES(po_value)
                      , received_value = VALUES(received_value)
                      , first_received = VALUES(first_received)
                      , last_received = VALUES(last_received)
                      , verified = VALUES(verified)